name: test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          # TODO: matrix
          python-version: "3.13"

      - uses: astral-sh/setup-uv@v3
      - run: uv sync
      - run: uv build
      - run: uv run ruff check
      - run: uv run ruff format --check
      - run: uv run pytest --cov=pydantic_ai_chat_ui --cov-report=term-missing -q
